#!/bin/sh
set -eu
shopt -s failglob

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

# Build 3rdparty libraries and upstream pdf2htmlEX
$BASEDIR/dobuilddependencies

# Build pdf2htmlEX-android
cd $BASEDIR
./gradlew assembleRelease

# Build sample app, to make sure everything works
cp $BASEDIR/pdf2htmlEX/build/outputs/aar/pdf2htmlex-android-release.aar $BASEDIR/android-sample-app/app/libs/pdf2htmlEX.aar
cd $BASEDIR/android-sample-app
./gradlew build

