#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

DB=$BASEDIR/dependency-builder
TARBALL_STORAGE=$DB/src/main/cpp/tarballs

# @TODO: issue #1
touch $DB/src/main/cpp/packages/glib-2.0.cmake

PARALLEL=true
CLEANUP=false
BUILD_TYPE="Release"

for i in "$@"
do
  if test "$i" = "--serial"
  then
    PARALLEL=false
  elif test "$i" = "--cleanup"
  then
    CLEANUP=true
  elif test "$i" = "--debug"
  then
    BUILD_TYPE="Debug"
  fi
done

# Build 3rdparty libraries and upstream pdf2htmlEX
cd $BASEDIR
./gradlew dependency-builder:assemble$BUILD_TYPE

run_build() {
  local build_target=$1
  cmake --build $build_target

  if "$CLEANUP"
  then
    #@TODO: no-force rm
    find $build_target -mindepth 1 -maxdepth 1 -type d -name '*-prefix' -exec rm -rf {} \;
  fi
}

pids=
for build_target in $(find $DB/.cxx/cmake -mindepth 2 -maxdepth 2)
do
  if "$PARALLEL"
  then
    ( run_build $build_target ) &
    pids="$pids $!"
  else
    run_build $build_target
  fi
done

for pid in $pids
do
  if ! wait $pid
  then
    echo "Build failed. Waiting for other subprocesses..."
    wait
    exit 1
  fi
done

