#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

# NDK-23 is the last to support api-16
NDK="23.2.8568313"
#NDK="25.0.8775105"

version_format='([0-9\.]+)'

expression="s/ndk-$version_format/ndk-$NDK/"
sed -E "--expression=$expression" -i $BASEDIR/README.md

expression="s/ndkVersion [\"\']$version_format[\"\']/ndkVersion '$NDK'/"
sed -E "--expression=$expression" -i $BASEDIR/pdf2htmlEX/build.gradle $BASEDIR/dependency-builder/build.gradle
