#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

NDK="22.0.7026061"

version_format='([0-9\.]+)'

expression="s/ANDROID_NDK\:([ ]+)\"$version_format\"/ANDROID_NDK\:\1\"$NDK\"/"
sed -E "--expression=$expression" -i $BASEDIR/.github/workflows/privilegedBuild.yml $BASEDIR/.github/workflows/unprivilegedBuild.yml

expression="s/ndk-$version_format/ndk-$NDK/"
sed -E "--expression=$expression" -i $BASEDIR/README.md

expression="s/ndkVersion \"$version_format\"/ndkVersion \"$NDK\"/"
sed -E "--expression=$expression" -i $BASEDIR/pdf2htmlEX/build.gradle $BASEDIR/dependency-builder/build.gradle $BASEDIR/android-sample-app/app/build.gradle $BASEDIR/aar-instrumented-tester/pdf2htmlEX/build.gradle 

