#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

function rm_folder_if_exists() {
  if test -d $BASEDIR/$1
  then
    rm -rf $BASEDIR/$1
  fi
}

function rm_file_if_exists() {
  if test -f $BASEDIR/$1
  then
    rm $BASEDIR/$1
  fi
}

rm_folder_if_exists pdf2htmlEX/.cxx
rm_folder_if_exists pdf2htmlEX/build
rm_folder_if_exists .gradle
rm_folder_if_exists build
rm_file_if_exists local.properties

rm_folder_if_exists application/app/.cxx
rm_folder_if_exists application/app/build
rm_folder_if_exists application/.gradle
rm_folder_if_exists application/build
rm_file_if_exists application/local.properties

rm_folder_if_exists dependency-builder/.cxx
rm_folder_if_exists dependency-builder/build

find $BASEDIR/dependency-builder/src/main/cpp/tarballs -mindepth 2 -maxdepth 2 -type f -exec rm {} \;
find $BASEDIR/dependency-builder/src/main/cpp/tarballs -mindepth 1 -maxdepth 1 -type d -exec rmdir {} \;

