#!/bin/sh
set -euo pipefail

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

function rm_folder_if_exists() {
  if test -d $BASEDIR/$1
  then
    rm -rf $BASEDIR/$1
  fi
}

function rm_file_if_exists() {
  if test -f $BASEDIR/$1
  then
    rm $BASEDIR/$1
  fi
}

rm_folder_if_exists pdf2htmlEX/.cxx
rm_folder_if_exists pdf2htmlEX/build
rm_folder_if_exists .gradle
rm_folder_if_exists build

rm_file_if_exists android-sample-app/app/libs/pdf2htmlEX.aar
rm_folder_if_exists android-sample-app/app/.cxx
rm_folder_if_exists android-sample-app/app/build
rm_folder_if_exists android-sample-app/.gradle
rm_folder_if_exists android-sample-app/build

rm_folder_if_exists dependency-builder/.cxx
rm_folder_if_exists dependency-builder/build

