#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

function rm_folder_if_exists() {
  if test -d $BASEDIR/$1
  then
    rm -rf $BASEDIR/$1
  fi
}

function rm_file_if_exists() {
  if test -f $BASEDIR/$1
  then
    rm $BASEDIR/$1
  fi
}

rm_folder_if_exists .idea
rm_file_if_exists pdf2htmlEX-Android.iml
rm_file_if_exists pdf2htmlEX/pdf2htmlEX.iml

rm_folder_if_exists android-sample-app/.idea
rm_file_if_exists android-sample-app/android-sample-app.iml
rm_file_if_exists android-sample-app/app/app.iml

rm_file_if_exists dependency-builder/dependency-builder.iml

