#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

DB=$BASEDIR/dependency-builder
TARBALL_STORAGE=$DB/src/main/cpp/tarballs


PARALLEL=true
for i in "$@"
do
  if test "$i" = "--serial"
  then
    PARALLEL=false
  fi
done

pids=
for package in $(find $DB/src/main/cpp/packages -mindepth 1 -maxdepth 1 -type f -name '*.cmake')
do
  URL=$(awk '/[^#]URL (.*)/{ print $2 }' $package)
  if test -n "$URL"
  then
    FILENAME=$(basename "$URL")
    if test ! -f "$TARBALL_STORAGE/$FILENAME"
    then
      wget --output-document="$TARBALL_STORAGE/$FILENAME" $URL &
      pid=$!
      if "$PARALLEL"
      then
        pids="$pids $pid"
      else
        wait $pid
      fi
    fi
  fi
done

for pid in $pids
do
  if ! wait $pid
  then
    echo "download failed. Waiting for other subprocesses..."
    wait
    echo "download failed.."
    exit 1
  fi
done

