#!/usr/bin/env perl
# (C) 2021 ViliusSutkus89@gmail.com

use warnings;
use strict;

use Getopt::Long;
use File::Basename;
use File::Copy;
use File::Path;

my ($project, $cmakeBinaryDir, $installPrefix);

Getopt::Long::GetOptions('project=s' => \$project, 'cmakeBinaryDir=s' => \$cmakeBinaryDir, 'installPrefix=s' => \$installPrefix) or die("BAD USAGE!\n");

my $projectSrcDir = "${cmakeBinaryDir}/${project}-prefix/src/${project}";
my $installPatchFile = File::Basename::dirname(__FILE__) . '/packages/' . $project . '-Patch-Install.sh';
if (-e $installPatchFile) {
    print "Executing $installPatchFile\n";
    exec("$installPatchFile $projectSrcDir $installPrefix") or die $!;
}
