#!/usr/bin/env perl
#  MIT License
#
#  Copyright (c) 2021 - 2022 ViliusSutkus89.com
#
#  https://github.com/ViliusSutkus89/Sample_Android_Library-MavenCentral-Instrumented_Tests
#  ci-scripts/updateDownstreamVersions - v2.0.0
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#
###########################################################################################
### The Purpose ### The Purpose ### The Purpose ### The Purpose ### The Purpose ### The ###
###########################################################################################
#  The purpose of this script is to update downstream (README.md, sample app) version to
#  match current library version.
###########################################################################################
### ~The Purpose~ # ~The Purpose~ # ~The Purpose~ # ~The Purpose~ # ~The Purpose~ # ~The~ #
###########################################################################################

use warnings;
use strict;

use File::Basename;
use lib File::Basename::dirname(__FILE__) . '/lib';
use fileUpdater;
use getVersion;

die(File::Basename::basename(__FILE__) . " takes no arguments!\n") if (@ARGV);

my $version = getVersion::getVersion();
my $versionCode = getVersion::getVersionCode();

print "::set-output name=version::$version\n";
print "::set-output name=versionCode::$versionCode\n";

my $rootDirectory = File::Basename::dirname(pathResolver::getAbsolutePath(File::Basename::dirname(__FILE__)));
my $versionUpdater = fileUpdater->new({ rootDirectory => $rootDirectory });

$versionUpdater->update('README.md', sub {
    $_ = shift;
    s/^(\s+implementation\s+['"]com\.viliussutkus89\:pdf2htmlex-android\:)[\d\.]+(['"])$/${1}${version}${2}/;
    return $_;
});

print "::set-output name=files::README.md\n";
